package pe.edu.uni.appclinica.view;

import pe.edu.uni.appclinica.model.PersonalModel;



/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/c/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware/
 */
public class MainView extends javax.swing.JFrame {

    /** Creates new form MainView */
    public MainView() {
        initComponents();
		  this.setExtendedState(MAXIMIZED_BOTH);
		  establecerTitulo();		  
    }
	 
	 private void establecerTitulo(){
		 PersonalModel model = (PersonalModel) Session.get("USUARIO");
		 String titulo = "CLINICA APP [ Usuario: " + model.getUsuario() + " ] ";
		 this.setTitle(titulo);
	 }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      menuArchivo = new javax.swing.JMenu();
      menuProceso = new javax.swing.JMenu();
      menuProcesoRegistrarPaciente = new javax.swing.JMenuItem();
      menuProcesoHospitalizacion = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("CLINICA APP [ Usuario: jtorres ]");

      menuArchivo.setText("Archivo");
      menuBar.add(menuArchivo);

      menuProceso.setText("Proceso");

      menuProcesoRegistrarPaciente.setText("Registrar paciente");
      menuProcesoRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesoRegistrarPacienteActionPerformed(evt);
         }
      });
      menuProceso.add(menuProcesoRegistrarPaciente);

      menuProcesoHospitalizacion.setText("Hospitalización");
      menuProcesoHospitalizacion.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesoHospitalizacionActionPerformed(evt);
         }
      });
      menuProceso.add(menuProcesoHospitalizacion);

      menuBar.add(menuProceso);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void menuProcesoRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoRegistrarPacienteActionPerformed
      RegistrarPacienteView view = new RegistrarPacienteView();
		desktopPane.add(view);
		view.setVisible(true);
   }//GEN-LAST:event_menuProcesoRegistrarPacienteActionPerformed

   private void menuProcesoHospitalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoHospitalizacionActionPerformed
      HospitalizarView view = new HospitalizarView();
		desktopPane.add(view);
		view.setVisible(true);
   }//GEN-LAST:event_menuProcesoHospitalizacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenu menuArchivo;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuProceso;
   private javax.swing.JMenuItem menuProcesoHospitalizacion;
   private javax.swing.JMenuItem menuProcesoRegistrarPaciente;
   // End of variables declaration//GEN-END:variables

}
