
SELECT * FROM DBO.PERSONAL;

INSERT INTO DBO.PERSONAL(NOMBRE,APELLIDO,TIPO,USUARIO,CLAVE)
VALUES('Jose','Torres','E','jtorres','123456');

INSERT INTO DBO.PERSONAL(NOMBRE,APELLIDO,TIPO,USUARIO,CLAVE)
VALUES('Carlos','Zapata','M','czapata','123456');
